image: docker:20

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

Build:
  stage: build
  tags:
    - docker
  script:
    - sed -i "s/ghcr.io/${CI_REGISTRY}/g" Dockerfile
    - sed -i "s/:master/:latest/g" Dockerfile
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:latest
      .
    - docker push $CI_REGISTRY_IMAGE:latest